server:
  port: 8080
spring:
  application:
    name: mqtt-paho
    
mqtt:
  broker-url: tcp://172.17.17.212:1883
  client-id: emqx-paho
  username: admin
  password: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiODc4ZjVlOGIwYmE3NDQ3YmE1OTIyNzE4NDE2MmRlZDIiLCJ1c2VybmFtZSI6ImFkbWluIn0.gQkcmaAcUzmCHQvzTnOC4xyW4cNjftpsb6yuBA6_rJ8
  cleanSession: true
  reconnect: true
  timeout: 100
  keepAlive: 100
  defaultTopic: testtopic
  qos: 2