server:
  port: 8081
spring:
  application:
    name: mqtt-paho
    
mqtt:
  broker-url: tcp://xuzhihao:1883
  client-id: java-server-paho
  username: admin
  password: admin
  cleanSession: true
  reconnect: true
  timeout: 100
  keepAlive: 100
  defaultTopic: testtopic
  qos: 2