server:
   port: 8080
   tomcat:
      accept-count: 1000
      max-connections: 8192
      threads:
        max: 800
        min-spare: 10
spring:
   application:
      name: jmeter
   datasource:
      url: jdbc:postgresql://127.0.0.1:5432/jmeter
      username: postgres
      password: postgres
mybatis:
  mapper-locations:
    - classpath*:net/**/mapper/*.xml