server:
   port: 8080
   tomcat:
      accept-count: 1000
      max-connections: 8192
      threads:
        max: 800
        min-spare: 10
spring:
   application:
      name: jmeter
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/db
      username: admin
      password: 123456
mybatis:
  mapper-locations:
    - classpath*:net/**/mapper/*.xml