server:
   port: 8080
   
spring:
    kafka:
        bootstrap-servers: xuzhihao:9092
        producer:
            # 重试次数
            retries: 3
            # 批量发送的消息数量
            batch-size: 16384
            # 32MB的批处理缓冲区
            buffer-memory: 33554432
        consumer:
            # 默认消费者组
            group-id: etl
            # 最早未被消费的offset
            auto-offset-reset: earliest
            # 批量一次最大拉取数据量
            max-poll-records: 1000
            # 自动提交
            auto-commit-interval: 1000
            enable-auto-commit: true