server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://xuzhihao:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:net/**/mapper/*.xml

logging:
  level:
    root: info
    net.xzh.gen: debug