server:
   port: 8080
logging:
   config: classpath:logback.xml
hbase:
   config:
      hbase.zookeeper.quorum: 172.17.17.137
      hbase.zookeeper.port: 2181
      hbase.zookeeper.znode: /hbase
      hbase.client.keyvalue.maxsize: 1572864000