server:
  port: 8080
spring:
  rabbitmq:
    addresses: xuzhihao:5672
    virtual-host: / # rabbitmq的虚拟host
    username: admin # rabbitmq的用户名
    password: admin # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

