server:
  port: 8080
spring:
  rabbitmq:
    host: xuzhihao # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: / # rabbitmq的虚拟host
    username: guest # rabbitmq的用户名
    password: guest # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

