server:
  port: 8080
spring:
  rabbitmq:
    addresses: 192.168.20.203:5672,192.168.20.204:5672,192.168.20.205:5672
    virtual-host: / # rabbitmq的虚拟host
    username: guest # rabbitmq的用户名
    password: guest # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

