spring:
  datasource:
    url: jdbc:mysql://xuzhihao:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: xuzhihao # Redis服务器地址
    database: 9 # Redis数据库索引（默认为0）
    port: 26380 # Redis服务器连接端口
    password: redis26380 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

rabbitmq:
  relayHost: xuzhihao
  relayPort: 61613
  virtualHost: /
  login: admin
  passcode: 123456