server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://xuzhihao:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: http://xuzhihao:9200
mybatis:
  mapper-locations:
    - classpath*:net/**/mapper/*.xml
