server:
  port: 8083

mqtt:
  broker-url: tcp://xuzhihao:1883
  server-id: java-server-mg
  client-id: java-client-mg
  username: admin
  password: admin
  cleanSession: true
  reconnect: true
  timeout: 1000
  keepAlive: 100
  defaultTopic: testtopic
  qos: 2