server:
  port: 8083

mqtt:
  broker-url: tcp://xuzhihao:1883
  server-id: rabbitmq-mqtt
  client-id: mqtt-paho
  username: admin
  password: admin
  cleanSession: true
  reconnect: true
  timeout: 1000
  keepAlive: 100
  defaultTopic: testtopic
  qos: 2