server:
  port: 8080

spring:
  application:
    name: activemq
  activemq:
    # broker-url: failover:(tcp://192.168.66.133:61616,tcp://192.168.66.133:61617,tcp://192.168.66.133:616168) # 连接地址
    broker-url: tcp://xuzhihao:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false
      max-connections: 10
      # 空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
      # 强制的连接过期时间
      expiry-timeout: 0
  # 指定发送模式 （点对点 false ， 发布订阅 true）
  jms:
    pub-sub-domain: false
    template:
      delivery-mode: persistent
# 自己定义目标名称（队列或主题）
activemq:
  qname: springboot_queue