sharding:
  jdbc:
    datasource:
      names: ds-0,ds-1
      ds-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.17.17.29:5432/ec_demo_0?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
        username: postgres
        password: vjsp2020
      ds-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.17.17.29:5432/ec_demo_1?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
        username: postgres
        password: vjsp2020
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: ds-$->{id % 2}
        tables:
          user:
            actual-data-nodes: ds-$->{0..1}.user_info
            key-generator-column-name: id
      props:
        sql:
          show: true