server:
  port: 8080

spring:
  application:
    name: sharding-jdbc
  profiles:
    active: sharding-tables
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  typeAliasesPackage: net.xzh.sharding.model